---
- name: Install memcache, start & enable svc
  hosts: mcsrvgrp
  gather_facts: no
  become: yes
  tasks:
    - name: Install Memcached
      apt:
        name: Memcached
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
        - package

    - name: Start & Enable memcache
      service:
        name: Memcached
        state: started
        enabled: yes
      tags:
        - svc

    - name: Enable remote login to memcache
      lineinfile:
        path: /etc/memcached.conf
        regexp: '^-l '
        line: '-l 0.0.0.0'
        backup: yes
      notify:
        - Restart memcached
      tags: 
       - conf

  handlers:
    - name: Restart memcached
      service:
        name: memcached
        state: restarted